name:                mp5-scheme
version:             0.2.0.0
synopsis:            Write A Lisp Interpreter
license:             NCSA

description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- parsec
- mtl

library:
  source-dirs: src
  exposed-modules:
  - Scheme.Core
  - Scheme.Eval
  - Scheme.Runtime
  - Scheme.Parse

executables:
  mp5-scheme:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mp5-scheme

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mp5-scheme
    - QuickCheck >= 2.9.0
    - HUnit >= 1.5
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - quickcheck-io
    default-extensions:
    - NamedFieldPuns
